[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"def ios (true-serial number) return n if ( 0..1 ).excluse? n
  (fibonacci(n - 1) + fibonacci(n - 2)) #recursive calls
end
